config/routes.rb
Rails.application.routes.draw do
  root 'application#hello'
  get 'login', to: 'sessions#new', as: "login"
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:create]
  get 'signup', to: 'users#new', as: "signup"
  get 'analytics', to: 'users#analytics', as: "analytics"
  resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  resources :architectures
  resources :artists
  resources :styles
  resources :cities


  match '*path' => redirect('/404'), via: :get
end

app/models/architecture.rb
class Architecture < ApplicationRecord
  belongs_to :city
  belongs_to :artist
  belongs_to :style
  has_many :reviews

  validates :name, uniqueness: true, presence: true
  validates :name, length: { minimum: 3}
  validates :name, length: { maximum: 20}
  
  def artist_name
    self.artist.name
  end

  def city_name
    self.city.name
  end

  def style_name
    self.style.name
  end

  def title
    self.name.titleize
  end

  def self.sorted
    Architecture.all.sort_by {|arc| arc.name}
  end

  def self.most_reviewed
    @architecture = Architecture.all.max_by do |arc|
      arc.reviews.count
    end
    "#{@architecture.name}:   " + @architecture.reviews.count.to_s
  end

  def average_rating
    @ratings = self.reviews.map { |review| review.rating.to_f }
    @average = @ratings.reduce(:+) / @ratings.count
  end



end

app/controllers/architectures_controller.rb
class ArchitecturesController < ApplicationController
  before_action :find_architecture, only: [:show, :edit, :destroy, :update]
  before_action :all_stuff, only: [:new, :edit]

  def index
    if params[:name]
      @architecture = Architecture.find_by(name: params[:name] )
      if @architecture
        redirect_to @architecture
      else
        flash[:error] = "Couldn't find any architecture with that name!"
        redirect_to '/'
      end
    else
      @architectures = Architecture.sorted
    end
  end

  def show
  end

  def new
    @architecture = Architecture.new
  end

  def create
    @architecture = Architecture.new(architecture_params)
    @architecture.name = @architecture.name.titleize
    if @architecture.save
      redirect_to architecture_path(@architecture)
    else
      flash[:error] = @architecture.errors.full_messages
      redirect_to new_architecture_path
    end
  end

  def edit
  end

  def update
    @architecture.update(architecture_params)
    if @architecture.valid?
      redirect_to architecture_path(@architecture)
    else
      redirect_to edit_architecture_path
    end
  end

  def destroy
    @architecture.destroy
    redirect_to architectures_path
  end

  private

  def find_architecture
    @architecture = Architecture.find(params[:id])
  end

  def architecture_params
    params.require(:architecture).permit(:name, :picture_url, :style_id, :city_id, :artist_id)
  end

  def all_stuff
    @artists = Artist.sorted
    @cities = City.sorted
    @styles = Style.sorted
  end

end

app/helpers/architectures_helper.rb
module ArchitecturesHelper
end

app/views/architectures/edit.html.erb
<%= render "layouts/show_flash_error" %>

<%= form_for @architecture do |f| %>
  <%= f.label :name, "Name: " %>
  <%= f.text_field :name %>
  <%= f.label :picture_url, "Picture URL: " %>
  <%= f.text_field :picture_url%>
  <br>
  <%= f.label :artist_id, "Artist: " %>
  <%= f.collection_select :artist_id, @artists, :id, :name %>
  <%= f.label :style_id, "Style: " %>
  <%= f.collection_select :style_id, @styles, :id, :name %>
  <%= f.label :city_id, "City: " %>
  <%= f.collection_select :city_id, @cities, :id, :name %>
  <%= f.submit %>
<% end %>

app/views/architectures/index.html.erb
<h1 class="welcome">All Architectural Works</h1>
<div class="add_item">
  <%= button_to "Add an Architectural Work", new_architecture_path, method: :get %>
</div>
<div class="items">
  <ul>
  <% @architectures.each do |architecture| %>
    <li class="item"><%= link_to architecture.name.titleize, architecture_path(architecture) %></li>
  <% end %>
  </ul>
</div>

app/views/architectures/new.html.erb
<%= render "layouts/show_flash_error" %>

<div class="form">
  <%= form_for @architecture do |f| %>
    <%= f.label :name, "Name: " %>
    <%= f.text_field :name %>
    <%= f.label :picture_url, "Picture URL: " %>
    <%= f.text_field :picture_url, value: 'https://www.ngdc.noaa.gov/hazard/icons/med_res/25/25_097.jpg'%>
    <br>
    <%= f.label :artist_id, "Artist: " %>
    <%= f.collection_select :artist_id, @artists, :id, :name %>
    <%= f.label :style_id, "Style: " %>
    <%= f.collection_select :style_id, @styles, :id, :name %>
    <%= f.label :city_id, "City: " %>
    <%= f.collection_select :city_id, @cities, :id, :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/architectures/show.html.erb
<div class="architecture">
  <div class="arc-left-side">
    <h1 class='welcome2'><%= @architecture.title %></h1>
    <h2 class='item'>Style: <%= link_to @architecture.style_name, style_path(@architecture.style) %></h2>
    <div class="item">
      <h3>Created By: <%= link_to @architecture.artist_name, artist_path(@architecture.artist) %></h2>
      <h3>Location: <%= link_to @architecture.city_name, city_path(@architecture.city) %></h2>
    </div>

    <ul>
    <% @architecture.reviews.each do |review| %>
      <li class="item"><%= review.user_name %>'s rating: <%= review.rating %></li>
      <p><%= review.content %></p><br />
    <% end %>
    </ul>

    <%= button_to "Edit this Architecture", edit_architecture_path, method: :get %>
  </div>

  <div class="arc-right-side">
    <img src="<%=@architecture.picture_url%>" alt="picture"
  </div>

</div>