config/routes.rb
Rails.application.routes.draw do
  root 'application#hello'
  get 'login', to: 'sessions#new', as: "login"
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:create]
  get 'signup', to: 'users#new', as: "signup"
  get 'analytics', to: 'users#analytics', as: "analytics"
  resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  resources :architectures
  resources :artists
  resources :styles
  resources :cities


  match '*path' => redirect('/404'), via: :get
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user, :require_logged_in
  helper_method :current_user, :logged_in?, :require_logged_in

  def current_user
    @user = User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def require_logged_in
    redirect_to '/login' unless logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/hello.html.erb
<% if flash[:error] %>
  <%= flash[:error] %>
<% end %>

<h1 class='welcome' >Welome to KEYSTONE <%= current_user.username %>!</h1>
<div class="home_review">
  <h3>My Reviews</h3>
  <div class="item">
  <% current_user.reviews.each do |review| %>
    Review for: <%= link_to review.architecture.name, architecture_path(review.architecture) %><br />
    Rating: <%= review.rating %><br />
    <li style="width:200px; max-width:200px; word-wrap:break-word;" ><%= review.content %><br /><br /></li>
    <div class="review_buttons">
      <%= button_to "Edit", edit_review_path(review), method: :get %>
      <%= button_to "Delete", review_path(review), method: :delete %><br /><br />
    </div>
  <% end %>
  </div>
</div>