config/routes.rb
Rails.application.routes.draw do
  root 'application#hello'
  get 'login', to: 'sessions#new', as: "login"
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:create]
  get 'signup', to: 'users#new', as: "signup"
  get 'analytics', to: 'users#analytics', as: "analytics"
  resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  resources :architectures
  resources :artists
  resources :styles
  resources :cities


  match '*path' => redirect('/404'), via: :get
end

app/views/layouts/_header.html.erb
<div class="heading" >
  <div class="left_block">
    <div class="title">

      <div class="logo">
        <i class="fa fa-university" ></i>
      </div>
      <%= link_to "KEYSTONE", '/'%>
    </div> 

    <div class="buttons">
      <a class="title_buttons"><%= button_to "Architecture", architectures_path, method: :get %></a>
      <a class="title_buttons"><%= button_to "Artists", artists_path, method: :get %></a>
      <a class="title_buttons"><%= button_to "Cities", cities_path, method: :get %></a>
      <a class="title_buttons"><%= button_to "Styles", styles_path, method: :get %></a>
      <a class="title_buttons"><%= button_to "Write a Review", new_review_path, method: :get %></a>
      <a class="title_buttons"><%= button_to "Analytics", analytics_path, method: :get %>

    </div>
  </div>

  <div class="middle_block">
    <a class="architecture_search">Search for Architecture:
    <%= form_tag(architectures_path, :method => "get") do %>
        <%= text_field_tag :name, params[:name]%>
        <%= submit_tag "Search" %>
    <% end %></a>

  </div>

  <div class="right_block">
    <a class ="log">
    <% if logged_in? %>
      <a class="login_status">Logged in as <br /><div class="item">
        <%= link_to current_user.username, '/'%>
      </a>
      </div>
        <%= button_to "Log out", logout_path, method: :delete %></a>
    <% else %>
      <% require_logged_in %>
    <% end %>
  </div>
</div>

app/views/layouts/_show_flash_error.html.erb
<div class="errors">
  <% if flash[:error] && flash[:error].last != "Need to log in!" %>
  <ul>
    <% flash[:error].each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2Project</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="new.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bowlby+One+SC|Diplomata|Fascinate|Plaster|Play|Roboto" rel="stylesheet">
  </head>

  <body>
      <%= render "layouts/header" unless @disable_nav %>
      <div class="container_bg">

      </div>
      <div class="container">
        <%= yield %>
      </div>
    </body>
</html>